server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    enabled: true
    key-store: classpath:keystore/pc-store.p12
    key-store-password: qweqwe
    key-alias: smart

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/smart
    username: smartadmin
    password: 6tfgv6zghb6
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
logging:
  level: info